import { Injectable } from '@nestjs/common';
import { TipoProductos } from 'src/productos/entities/enum-productos';
import {
  DificultadDeCuidado,
  Estacion,
  FrecuenciaDeRiego,
  Habitat,
  LuzRequerida,
  NivelDeHumedad,
  TipoDeSuelo,
} from '../entities/enum-plantas';
import { Planta } from '../entities/planta.entity';
import { CreatePlantaDto } from '../dto/create-planta.dto';

@Injectable()
export class PlantasService {
  plantas: Planta[] = [];
  constructor() {
    this.plantas = [
      new Planta(
        12,
        'Cactus Opuntia',
        [
          'https://acdn.mitiendanube.com/stores/001/202/679/products/opuntia-microdasys-amarilla11-f96f80e136ac2b347816196560098082-1024-1024.webp'],
        10,
        8360,
        ['Arica a Pta.Arenas'],
        10,
        'Es un cactus firme y decorativo.',
        TipoProductos.Planta,
        4,
        150,
        'PL1',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.MENSUAL,
        NivelDeHumedad.BAJA,
        20,
        false,
        150,
        TipoDeSuelo.ARENOSO,
        DificultadDeCuidado.BAJA,
        Estacion.PRIMAVERA,
        [],
        [],
      ),
      new Planta(
        13,
        'Lengua de Suegra',
        [
          'https://lepotit.cl/cdn/shop/products/SansevieriaMAutorreganteSblanco_860x.jpg?v=1633118960',
        ],
        12,
        12900,
        ['Arica a Pta.Arenas'],
        55,
        'Es una planta de interior popular.',
        TipoProductos.Planta,
        1,
        100,
        'PL2',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.MENSUAL,
        NivelDeHumedad.BAJA,
        18,
        true,
        150,
        TipoDeSuelo.ARCILLOSO,
        DificultadDeCuidado.BAJA,
        Estacion.PRIMAVERA,
        [],
        [],
      ),
      new Planta(
        14,
        'Lirio de Agua',
        [
          'https://acdn.mitiendanube.com/stores/001/202/679/products/231-ad700e1f90d14e71ed16246336798562-1024-1024.webp',
        ],
        20,
        8360,
        ['Arica a Pta.Arenas'],
        12,
        'Es una planta acuática decorativa.',
        TipoProductos.Planta,
        4,
        120,
        'PL3',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.MENSUAL,
        NivelDeHumedad.MEDIA,
        22,
        false,
        200,
        TipoDeSuelo.ARCILLOSO,
        DificultadDeCuidado.MEDIA,
        Estacion.VERANO,
        [],
        [],
      ),
      new Planta(
        15,
        'Monstera deliciosa',
        [
          'https://www.kenaz.cl/cdn/shop/products/monstera-946603.jpg?v=1718161088&width=600',
        ],
        17,
        7456,
        ['Arica a Pta.Arenas'],
        10,
        'Es una planta tropical ideal para interiores.',
        TipoProductos.Planta,
        3,
        130,
        'PL4',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.ALTA,
        25,
        true,
        180,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.MEDIA,
        Estacion.OTONO,
        [],
        [],
      ),
      new Planta(
        16,
        'Helecho',
        [
          'https://cdnx.jumpseller.com/mentaconcept/image/41835179/resize/480/480?1699388964',
        ],
        18,
        9000,
        ['Arica a Pta.Arenas'],
        32,
        'Es una planta común en ambientes húmedos.',
        TipoProductos.Planta,
        2,
        180,
        'PL5',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.ALTA,
        23,
        false,
        300,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.MEDIA,
        Estacion.VERANO,
        [],
        [],
      ),
      new Planta(
        17,
        'Ficus lyrata',
        [
          'https://viverolosaromos.com/wp-content/uploads/2023/11/EXALTATA-HELECHO-510x510.webp',
        ],
        22,
        5779,
        ['Arica a Pta.Arenas'],
        20,
        'Es una planta popular de gran tamaño.',
        TipoProductos.Planta,
        5,
        300,
        'PL6',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.MEDIA,
        20,
        false,
        400,
        TipoDeSuelo.LIMOSO,
        DificultadDeCuidado.MEDIA,
        Estacion.PRIMAVERA,
        [],
        [],
      ),
      new Planta(
        18,
        'Filodendro Longipetiolatum',
        [
          'https://www.kenaz.cl/cdn/shop/products/peperomia-cucharita-561186.jpg?v=1701109062&width=600',
        ],
        30,
        5320,
        ['Arica a Pta.Arenas'],
        100,
        'Es una planta tropical común.',
        TipoProductos.Planta,
        1,
        90,
        'PL7',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.MEDIA,
        22,
        false,
        180,
        TipoDeSuelo.ARCILLOSO,
        DificultadDeCuidado.MEDIA,
        Estacion.PRIMAVERA,
        [],
        [],
      ),
      new Planta(
        19,
        'Peperomia obtusifolia',
        [
          'https://d17jkdlzll9byv.cloudfront.net/wp-content/uploads/2023/06/ficus-lyrata-0002-900x900.jpg',
        ],
        25,
        9425,
        ['Arica a Pta.Arenas'],
        34,
        'Es una planta compacta y popular en interiores.',
        TipoProductos.Planta,
        2,
        120,
        'PL8',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.MEDIA,
        18,
        true,
        200,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.MEDIA,
        Estacion.OTONO,
        [],
        [],
      ),
      new Planta(
        20,
        'Pilea peperomioides',
        [
          'https://www.aprilplants.com/cdn/shop/products/Eucalipto_silver_dollar_copa_22o_cocoblanca_planta-de-exterior-aromatica_1024x.jpg?v=1679046875',
        ],
        40,
        7530,
        ['Arica a Pta.Arenas'],
        25,
        'Es una planta compacta y decorativa.',
        TipoProductos.Planta,
        1,
        100,
        'PL9',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.MEDIA,
        22,
        false,
        300,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.MEDIA,
        Estacion.OTONO,
        [],
        [],
      ),
      new Planta(
        21,
        'Dollar variegado',
        [
          'https://d17jkdlzll9byv.cloudfront.net/wp-content/uploads/2024/02/philodendron-longifolio-00001.jpg',
        ],
        30,
        6900,
        ['Arica a Pta.Arenas'],
        50,
        'Es una planta tropical de hojas variegadas.',
        TipoProductos.Planta,
        4,
        200,
        'PL10',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.ALTA,
        22,
        true,
        300,
        TipoDeSuelo.ARCILLOSO,
        DificultadDeCuidado.ALTA,
        Estacion.VERANO,
        [],
        [],
      ),
      new Planta(
        22,
        'Oulluy',
        ['https://m.media-amazon.com/images/I/51rjakslj5L._AC_SX569_.jpg'],
        50,
        9120,
        ['Arica a Pta.Arenas'],
        60,
        'Es una planta suculenta decorativa.',
        TipoProductos.Planta,
        5,
        300,
        'PL11',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.MEDIA,
        24,
        true,
        300,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.MEDIA,
        Estacion.VERANO,
        [],
        [],
      ),
      new Planta(
        23,
        'Begonia',
        [
          'https://vitaflor.cl/wp-content/uploads/2022/12/aloe-striata-1536x1152.jpg.webp',
        ],
        30,
        1110,
        ['Arica a Pta.Arenas'],
        100,
        'Es una planta ornamental común.',
        TipoProductos.Planta,
        1,
        100,
        'PL12',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.ALTA,
        20,
        false,
        180,
        TipoDeSuelo.LIMOSO,
        DificultadDeCuidado.MEDIA,
        Estacion.VERANO,
        [],
        [],
      ),
      new Planta(
        24,
        'Alocasia',
        [
          'https://imgix.be.green/63860658cd20e331480209.jpg?w=1200&h=1200&auto=compress',
        ],
        15,
        5150,
        ['Arica a Pta.Arenas'],
        45,
        'Es una planta de interior elegante y tropical.',
        TipoProductos.Planta,
        1,
        90,
        'PL13',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.MENSUAL,
        NivelDeHumedad.ALTA,
        22,
        true,
        120,
        TipoDeSuelo.LIMOSO,
        DificultadDeCuidado.MEDIA,
        Estacion.PRIMAVERA,
        [],
        [],
      ),
      new Planta(
        25,
        'Syngonium',
        [
          'https://www.cactussuculovers.cl/wp-content/uploads/2020/08/086b3977-dab8-4a35-bbcd-0b93596504ce-copia.jpg',
        ],
        18,
        6150,
        ['Arica a Pta.Arenas'],
        34,
        'Es una planta decorativa de hojas en forma de flecha.',
        TipoProductos.Planta,
        2,
        80,
        'PL14',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.ALTA,
        24,
        false,
        140,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.MEDIA,
        Estacion.OTONO,
        [],
        [],
      ),
      new Planta(
        26,
        'Pachira Aquatica',
        [
          'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRD4KlhDv3R0dc7SRP8XjrDIRjumKFmpv1J6pA2tW_XQ6JgsXUl',
        ],
        22,
        7530,
        ['Arica a Pta.Arenas'],
        50,
        'Es una planta de interior con tronco decorativo.',
        TipoProductos.Planta,
        3,
        120,
        'PL15',
        Habitat.INTERIOR,
        LuzRequerida.ALTA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.MEDIA,
        20,
        true,
        200,
        TipoDeSuelo.LIMOSO,
        DificultadDeCuidado.MEDIA,
        Estacion.VERANO,
        [],
        [],
      ),
      new Planta(
        27,
        'Begonia Rex',
        [
          'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRD4KlhDv3R0dc7SRP8XjrDIRjumKFmpv1J6pA2tW_XQ6JgsXUl',
        ],
        10,
        6100,
        ['Arica a Pta.Arenas'],
        60,
        'Es una begonia decorativa con hojas de colores vivos.',
        TipoProductos.Planta,
        2,
        110,
        'PL16',
        Habitat.INTERIOR,
        LuzRequerida.MEDIA,
        FrecuenciaDeRiego.SEMANAL,
        NivelDeHumedad.ALTA,
        18,
        true,
        100,
        TipoDeSuelo.TURBA,
        DificultadDeCuidado.ALTA,
        Estacion.PRIMAVERA,
        [],
        [],
      ),
    ];
  }
  obtCantidadPlantas() {
    const cantidadPlantas = this.plantas.length;
    return cantidadPlantas;
  }
  createCodigoPlanta() {
    const numeroCodigo = this.obtCantidadPlantas() + 1;
    const codigoPLanta = 'PL' + numeroCodigo;
    return codigoPLanta;
  }

  create(
    createPlantaDto: CreatePlantaDto,
    idProducto: number,
    codigoProducto: string,
  ) {
    const crePlanta: Planta = new Planta(
      idProducto,
      createPlantaDto.nombreProducto,
      createPlantaDto.imagenProducto,
      createPlantaDto.descuento,
      createPlantaDto.precioNormal,
      createPlantaDto.coberturaDeDespacho,
      createPlantaDto.stock,
      createPlantaDto.descripcionProducto,
      TipoProductos.Planta,
      0,
      0,
      codigoProducto,
      createPlantaDto.habitat,
      createPlantaDto.luz,
      createPlantaDto.frecuenciaDeRiego,
      createPlantaDto.humedadIdeal,
      createPlantaDto.temperaturaIdeal,
      createPlantaDto.toxicidadMascotas,
      createPlantaDto.tamanoMaximo,
      createPlantaDto.tipoSuelo,
      createPlantaDto.dificultadDeCuidado,
      createPlantaDto.estacion,
      createPlantaDto.fertilizantesSugeridos,
      createPlantaDto.sustratosSugeridos,
    );

    this.plantas.push(crePlanta);
    return crePlanta;
  }

  findAll() {
    return this.plantas;
  }

  findOne(id: number) {
    const plantaEncontrada = this.plantas.find(
      (prod) => prod.idProducto === id,
    );

    if (plantaEncontrada) {
      return plantaEncontrada;
    }
    return null;
  }
}
